# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] ="../platforms"

class Ui_call_api_decrypt_2(object):
    def setupUi(self, call_api_decrypt_2):
        call_api_decrypt_2.setObjectName("call_api_decrypt_2")
        call_api_decrypt_2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(call_api_decrypt_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 60, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(230, 150, 351, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 150, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 230, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 290, 61, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(230, 230, 351, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(230, 290, 351, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.call_api_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.call_api_encrypt.setGeometry(QtCore.QRect(230, 400, 75, 23))
        self.call_api_encrypt.setObjectName("call_api_encrypt")
        self.call_api_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.call_api_decrypt.setGeometry(QtCore.QRect(490, 400, 75, 23))
        self.call_api_decrypt.setObjectName("call_api_decrypt")
        call_api_decrypt_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(call_api_decrypt_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        call_api_decrypt_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(call_api_decrypt_2)
        self.statusbar.setObjectName("statusbar")
        call_api_decrypt_2.setStatusBar(self.statusbar)

        self.retranslateUi(call_api_decrypt_2)
        QtCore.QMetaObject.connectSlotsByName(call_api_decrypt_2)

    def retranslateUi(self, call_api_decrypt_2):
        _translate = QtCore.QCoreApplication.translate
        call_api_decrypt_2.setWindowTitle(_translate("call_api_decrypt_2", "MainWindow"))
        self.label.setText(_translate("call_api_decrypt_2", "CEASAR CIPHER"))
        self.label_2.setText(_translate("call_api_decrypt_2", "Plain Text"))
        self.label_3.setText(_translate("call_api_decrypt_2", "Key"))
        self.label_4.setText(_translate("call_api_decrypt_2", "CipherText"))
        self.call_api_encrypt.setText(_translate("call_api_decrypt_2", "Encrypt"))
        self.call_api_decrypt.setText(_translate("call_api_decrypt_2", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    call_api_decrypt_2 = QtWidgets.QMainWindow()
    ui = Ui_call_api_decrypt_2()
    ui.setupUi(call_api_decrypt_2)
    call_api_decrypt_2.show()
    sys.exit(app.exec_())
